import fs from 'fs';
import path from 'path';

const sidebars = {};
const docsPath = path.resolve(process.cwd(), 'docs');

const ignoreFolders = ['images', 'img', 'assets', '.DS_Store'];

if (fs.existsSync(docsPath)) {
  const topLevelFolders = fs.readdirSync(docsPath, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory() && !ignoreFolders.includes(dirent.name));

  topLevelFolders.forEach(topFolder => {
    const topName = topFolder.name;
    const subDirPath = path.join(docsPath, topName);

    // 读取二级目录并过滤
    const subFolders = fs.readdirSync(subDirPath, { withFileTypes: true })
      .filter(dirent => dirent.isDirectory() && !ignoreFolders.includes(dirent.name));

    if (subFolders.length > 0) {
      // 有二级目录时：生成完全隔离的独立侧边栏
      subFolders.forEach(subFolder => {
        const subName = subFolder.name;
        sidebars[`${topName}_${subName}`] = [
          {
            type: 'autogenerated',
            dirName: `${topName}/${subName}`
          }
        ];
      });
    } else {
      // 🌟 修复的地方在这里：没有二级目录时，ID 必须带上 Sidebar 后缀！
      sidebars[`${topName}Sidebar`] = [
        {
          type: 'autogenerated',
          dirName: topName
        }
      ];
    }
  });
}

export default sidebars;